### ISSUE TITLE
在某些主题下跳转的不太正常

### ISSUE THREAD

**Issue by hujy23** [wuruowuxin74/MenuTree#1]
你好(°∀°)ﾉ这个插件很棒，不过在某些主题下跳转的不太正常。

例如这个[Modelsim 基础使用教程 - 审问明辨笃行的小站](https://hujiyuan.cn/index.php/archives/1031/)

不太好描述这个情况，大概就是博客主题里页面上面有一个悬浮栏，目录跳转后，会被它挡住一些。

请问要如何解决这个问题呢？本人编程小白_(:з」∠)_

**Comment by wuruowuxin74** [comment]
@hujy23 这个问题已经处理过了,可以更新下代码,然后在你的样式表中增加样式,偏移量根据你顶部浮层高度调整 .menu-target-fix{display: block;position: relative;top: -60px;}

**Comment by hujy23** [comment]
@wuruowuxin74 感谢(°∀°)ﾉ解决了。不过对于小白来说，用法上完全不明白。第一感觉是在正文里用，就是用在 `<!-- index-menu -->` 里，但不知道怎么加，应该不是这里。就去查什么是 `样式表`，发现好像是CSS，然后去哪里改呢，去博客后台的主题编辑里面看了看，都是什么 `post.php` 之类的文件，读了读感觉应该不是这里。又想了想好像应该是去博客主题的css目录里面，发现一个叫 `customs.css` ，看起来应该是改它。打开一看好像乱码一样不知道加在那里，随便加到开头，强制刷新页面，发现都乱了。然后硬着头皮读，发现一个 `#main`，加在这个里面才对_(:з」∠)_ #小白瞎jb搞系列

```css
.h1,.h2,.h3,.h4,.lead,body,h1,h2,h3,h4,{font-family:RobotoDraft,Roboto,"Helvetica Neue",Helvetica,"Segoe UI","Microsoft YaHei",arial,sans-serif;font-weight:400}p{line-height: 25px}body>.container{margin-top:20px;margin-bottom:60px}footer{margin:0;bottom:0;left:0;right:0;z-index:5;height:50px;box-shadow:0 0 10px #202020}#main{padding-top:80px}.menu-target-fix{display: block;position: relative;top: -60px;}.navbar.navbar-inverse{border:0;box-shadow:0 0 10px #000;background-color:rgba(63,81,181,.92)}.billboard{background:#b8d9fa url(../img/billboard.jpg) center center repeat-x;background-size:cover;padding:170px 0 100px;box-shadow:0 2px 8px rgba(0,0,0,.25),0 2px 8px rgba(0,0,0,.12)}.billboard .intro{color:#fff;text-shadow:0 0 15px #202020}.post-meta{color:#999;font-size:11px;margin:10px 5px}.post-title{font-size:28px;line-height:1.7em;margin-top:5px}.post-content,.post-meta,.post-title{padding:0 30px}.post-title a{text-decoration:none}.post-content{overflow:auto}.page-navigator{display:inline-block;padding-left:0;margin:20px 0;border-radius:4px}.page-navigator li.current{color:#FFF;background:#323C3F none repeat scroll 0 0}.page-navigator>li{display:inline}.page-navigator>li:first-child>a,.page-navigator>li:first-child>span{margin-left:0;border-bottom-left-radius:4px;border-top-left-radius:4px}.page-navigator>.current>a,.page-navigator>.current>a:focus,.page-navigator>.current>a:hover,.page-navigator>.current>span,.page-navigator>.current>span:focus,.page-navigator>.current>span:hover{z-index:2;color:#fff;cursor:default;background-color:#428bca;border-color:#428bca}.page-navigator>.active>a,.page-navigator>.active>a:focus,.page-navigator>.active>a:hover,.page-navigator>.active>span,.page-navigator>.active>span:focus,.page-navigator>.active>span:hover{z-index:2;color:#fff;cursor:default;background-color:#428bca;border-color:#428bca}.page-navigator>li>a,.page-navigator>li>span{position:relative;float:left;padding:6px 12px;margin-left:-1px;line-height:1.428571429;text-decoration:none;background-color:#fff;border:1px solid #ddd}#search-btn{padding:10px;border-radius:25px;height:32px;width:32px;font-size:14px}.col-md-3 .panel .item{position:relative;display:block;padding:10px 15px;margin-bottom:-1px;border:1px solid #EEE;color:#555;text-decoration:none;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;word-break:break-all}.col-md-3 .panel a.panel-heading{display:block;text-decoration:none}a:hover.item{background-color:#eee}footer .footer-bottom{background:rgba(27,33,34,.92)}footer .footer-bottom{color:#aaa;padding:10px 0;font-size:12px}div.copyright,ul.footer-nav{padding:6px 0}.pull-left{float:left!important}div.copyright,ul.footer-nav{padding:6px 0}.pull-right{float:right!important}footer .footer-bottom ul.footer-nav li:first-child{border-left:0}footer .footer-bottom ul.footer-nav li{list-style:none;display:inline-block;padding:0 15px;border-left:1px solid #fff}footer .footer-bottom ul.footer-nav li a{color:#aaa;-webkit-transition:all .2s ease;-moz-transition:all .2s ease;-o-transition:all .2s ease;transition:all .2s ease}#comments,.tags{padding:16px}.comment-list{list-style:none;border-radius:0;padding-left:0;margin-bottom:0}#comments .comment-list li{position:relative;display:block;background-color:#FFF;padding:10px 10px 0;box-shadow:0 3px 8px rgba(0,0,0,.23),0 3px 8px rgba(0,0,0,.16);border:0;border-radius:0;margin-bottom:15px;line-height:1.5em;overflow:hidden}.comment-author{float:left}cite.fn{font-weight:bolder}.comment-meta{float:right}.comment-content{content:" ";display:table;clear:both;font-size:14px;padding:10px 0}.cancel-comment-reply,.comment-reply{text-align:right}#reply-button{border-radius:25px;padding:10px;margin-top:0;font-size:16px}#logo{display:none}@media(max-width:768px){#logo {display:inline}}.panel.panel-default>.panel-body>.post-content>p>img{max-width: 100%}@media (max-width: 700px){footer .footer-bottom ul.footer-nav {display: none;}.post-title{font-size:20px;}}
```
